#file: noinspection YAMLSchemaValidation
spring:
  application:
    name: titer

  datasource:
    url: jdbc:postgresql://localhost:5432
    username: titer_user
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true

app:
  security:
    jwt:
      secret: "w6MG6ScHfY6GYVNgyTd1pnbaZzH/Wn/akM0EPn7/I14="
      expiration-seconds: 86_400
      issuer: "titer-backend-eefbd064-569b-428c-a68c-bd7d94b7be64"

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,modulith
