#file: noinspection YAMLSchemaValidation
spring:
  application:
    name: titer

  datasource:
    url: jdbc:postgresql://localhost:5432/titer
    username: titer_user
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

app:
  security:
    jwt-secret: "fF1ydJYfTJwJDXZDAOLzk9CZIeQJPBuaflmrpanodEz"
    jwt-expiration-ms: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,modulith
