import { Component, OnInit } from '@angular/core';
import { GalleryComponent } from '../gallery/gallery.component';
import { PlayDetails } from '../../shared/interfaces/play-details.interface';

@Component({
  selector: 'app-trending',
  imports: [GalleryComponent],
  templateUrl: './trending.component.html',
  styleUrl: './trending.component.css',
})
export class TrendingComponent implements OnInit {
  mockPlays: PlayDetails[] = [
    {
      playId: '1',
      title: 'The Shawshank Redemption',
      director: { directorId: '1', directorName: 'Frank Darabont' },
      synopsis: '',
      releaseYear: 1994,
      rating: 1 + Math.round(Math.random() * 5 * 10) / 10,
      watchCount: Math.floor(Math.random() * (1_000_000 * 10)),
      reviewCount: Math.floor(Math.random() * (1_000_000 * 10)),
      posterImageUrl:
        'https://image.tmdb.org/t/p/w600_and_h900_bestv2/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
      directors: [],
      mainActors: [],
      genres: [],
      duration: 30 + Math.floor(Math.random() * 120),
      premiereDate: new Date(),
      premiereTheatre: { theatreId: '1', theatreName: 'Theatre 1' },
      cast: [],
      crew: [],
      releases: [],
      socials: [],
      comments: [],
    },
    {
      playId: '2',
      title: 'The Godfather',
      director: { directorId: '1', directorName: 'Francis Ford Coppola' },
      synopsis: '',
      releaseYear: 1972,
      rating: 1 + Math.round(Math.random() * 5 * 10) / 10,
      watchCount: Math.floor(Math.random() * (1_000_000 * 10)),
      reviewCount: Math.floor(Math.random() * (1_000_000 * 10)),
      posterImageUrl:
        'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
      directors: [],
      mainActors: [],
      genres: [],
      duration: 30 + Math.floor(Math.random() * 120),
      premiereDate: new Date(),
      premiereTheatre: { theatreId: '1', theatreName: 'Theatre 1' },
      cast: [],
      crew: [],
      releases: [],
      socials: [],
      comments: [],
    },
    {
      playId: '3',
      title: "Schindler's List",
      director: { directorId: '1', directorName: 'Steven Spielberg' },
      synopsis: '',
      releaseYear: 1993,
      rating: 1 + Math.round(Math.random() * 5 * 10) / 10,
      watchCount: Math.floor(Math.random() * (1_000_000 * 10)),
      reviewCount: Math.floor(Math.random() * (1_000_000 * 10)),
      posterImageUrl:
        'https://image.tmdb.org/t/p/w600_and_h900_bestv2/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
      directors: [],
      mainActors: [],
      genres: [],
      duration: 30 + Math.floor(Math.random() * 120),
      premiereDate: new Date(),
      premiereTheatre: { theatreId: '1', theatreName: 'Theatre 1' },
      cast: [],
      crew: [],
      releases: [],
      socials: [],
      comments: [],
    },
    {
      playId: '4',
      title: 'The Dark Knight',
      director: { directorId: '1', directorName: 'Christopher Nolan' },
      synopsis: '',
      releaseYear: 2008,
      rating: 1 + Math.round(Math.random() * 5 * 10) / 10,
      watchCount: Math.floor(Math.random() * (1_000_000 * 10)),
      reviewCount: Math.floor(Math.random() * (1_000_000 * 10)),
      posterImageUrl:
        'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
      directors: [],
      mainActors: [],
      genres: [],
      duration: 30 + Math.floor(Math.random() * 120),
      premiereDate: new Date(),
      premiereTheatre: { theatreId: '1', theatreName: 'Theatre 1' },
      cast: [],
      crew: [],
      releases: [],
      socials: [],
      comments: [],
    },
    {
      playId: '5',
      title: 'Spirited Away',
      director: { directorId: '1', directorName: 'Hayao Miyazaki' },
      synopsis: '',
      releaseYear: 2001,
      rating: 1 + Math.round(Math.random() * 5 * 10) / 10,
      watchCount: Math.floor(Math.random() * (1_000_000 * 10)),
      reviewCount: Math.floor(Math.random() * (1_000_000 * 10)),
      posterImageUrl:
        'https://image.tmdb.org/t/p/w600_and_h900_bestv2/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
      directors: [],
      mainActors: [],
      genres: [],
      duration: 30 + Math.floor(Math.random() * 120),
      premiereDate: new Date(),
      premiereTheatre: { theatreId: '1', theatreName: 'Theatre 1' },
      cast: [],
      crew: [],
      releases: [],
      socials: [],
      comments: [],
    },
    {
      playId: '6',
      title: 'Parasite',
      director: { directorId: '1', directorName: 'Bong Joon-Ho' },
      synopsis: '',
      releaseYear: 2019,
      rating: 1 + Math.round(Math.random() * 5 * 10) / 10,
      watchCount: Math.floor(Math.random() * (1_000_000 * 10)),
      reviewCount: Math.floor(Math.random() * (1_000_000 * 10)),
      posterImageUrl:
        'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
      directors: [],
      mainActors: [],
      genres: [],
      duration: 30 + Math.floor(Math.random() * 120),
      premiereDate: new Date(),
      premiereTheatre: { theatreId: '1', theatreName: 'Theatre 1' },
      cast: [],
      crew: [],
      releases: [],
      socials: [],
      comments: [],
    },
    {
      playId: '7',
      title: 'The Green Mile',
      director: { directorId: '1', directorName: 'Frank Darabont' },
      synopsis: '',
      releaseYear: 2000,
      rating: 1 + Math.round(Math.random() * 5 * 10) / 10,
      watchCount: Math.floor(Math.random() * (1_000_000 * 10)),
      reviewCount: Math.floor(Math.random() * (1_000_000 * 10)),
      posterImageUrl:
        'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
      directors: [],
      mainActors: [],
      genres: [],
      duration: 30 + Math.floor(Math.random() * 120),
      premiereDate: new Date(),
      premiereTheatre: { theatreId: '1', theatreName: 'Theatre 1' },
      cast: [],
      crew: [],
      releases: [],
      socials: [],
      comments: [],
    },
    {
      playId: '8',
      title: 'Pulp Fiction',
      director: { directorId: '1', directorName: 'Quentin Tarantino' },
      synopsis: '',
      releaseYear: 1995,
      rating: 1 + Math.round(Math.random() * 5 * 10) / 10,
      watchCount: Math.floor(Math.random() * (1_000_000 * 10)),
      reviewCount: Math.floor(Math.random() * (1_000_000 * 10)),
      posterImageUrl:
        'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg',
      directors: [],
      mainActors: [],
      genres: [],
      duration: 30 + Math.floor(Math.random() * 120),
      premiereDate: new Date(),
      premiereTheatre: { theatreId: '1', theatreName: 'Theatre 1' },
      cast: [],
      crew: [],
      releases: [],
      socials: [],
      comments: [],
    },
    {
      playId: '9',
      title: 'Your Name',
      director: { directorId: '1', directorName: 'Makoto Shinkai' },
      synopsis: '',
      releaseYear: 2017,
      rating: 1 + Math.round(Math.random() * 5 * 10) / 10,
      watchCount: Math.floor(Math.random() * (1_000_000 * 10)),
      reviewCount: Math.floor(Math.random() * (1_000_000 * 10)),
      posterImageUrl:
        'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/q719jXXEzOoYaps6babgKnONONX.jpg',
      directors: [],
      mainActors: [],
      genres: [],
      duration: 30 + Math.floor(Math.random() * 120),
      premiereDate: new Date(),
      premiereTheatre: { theatreId: '1', theatreName: 'Theatre 1' },
      cast: [],
      crew: [],
      releases: [],
      socials: [],
      comments: [],
    },
    {
      playId: '10',
      title: 'The Lord of the Rings: The return of the king',
      director: { directorId: '1', directorName: 'Peter Jackson' },
      synopsis: '',
      releaseYear: 2003,
      rating: 1 + Math.round(Math.random() * 5 * 10) / 10,
      watchCount: Math.floor(Math.random() * (1_000_000 * 10)),
      reviewCount: Math.floor(Math.random() * (1_000_000 * 10)),
      posterImageUrl:
        'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
      directors: [],
      mainActors: [],
      genres: [],
      duration: 30 + Math.floor(Math.random() * 120),
      premiereDate: new Date(),
      premiereTheatre: { theatreId: '1', theatreName: 'Theatre 1' },
      cast: [],
      crew: [],
      releases: [],
      socials: [],
      comments: [],
    },
  ];

  plays: PlayDetails[] = [];

  ngOnInit() {
    for (let i = 0; i < 5; i++) {
      const randomPlay =
        this.mockPlays[Math.floor(Math.random() * this.mockPlays.length)];

      this.plays.push(randomPlay);

      const rmIndex = this.mockPlays.findIndex(
        (mp) => mp.playId === randomPlay.playId,
      );
      this.mockPlays.splice(rmIndex, 1);
    }
  }
}
