CREATE SCHEMA users;

CREATE TABLE users.users
(
    id              UUID PRIMARY KEY DEFAULT uuidv7(),
    username        VARCHAR(20)  NOT NULL UNIQUE,
    email           VARCHAR(255) NOT NULL UNIQUE,
    first_name      VARCHAR(100),
    last_name       VARCHAR(100),
    profile_picture VARCHAR(2048)
);

CREATE TABLE users.user_auths
(
    provider_id   VARCHAR(255),
    password_hash VARCHAR(255),
    user_id       UUID        NOT NULL,
    provider      VARCHAR(20) NOT NULL,
    CONSTRAINT pk_user_auths PRIMARY KEY (user_id, provider),
    CONSTRAINT fk_user_auth_on_users FOREIGN KEY (user_id) REFERENCES users.users (id)
);

CREATE TABLE users.roles
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(50)                                         NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE users.permissions
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(100)                                        NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE users.role_permissions
(
    permission_id BIGINT NOT NULL,
    role_id       BIGINT NOT NULL,
    CONSTRAINT pk_role_permissions PRIMARY KEY (permission_id, role_id),
    CONSTRAINT fk_role_permissions_on_roles FOREIGN KEY (role_id) REFERENCES users.roles (id),
    CONSTRAINT fk_role_permissions_on_permissions FOREIGN KEY (permission_id) REFERENCES users.permissions (id)
);

CREATE TABLE users.user_roles
(
    role_id BIGINT NOT NULL,
    user_id UUID   NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id),
    CONSTRAINT fk_user_roles_on_users FOREIGN KEY (user_id) REFERENCES users.users (id),
    CONSTRAINT fk_user_roles_on_roles FOREIGN KEY (role_id) REFERENCES users.roles (id)
);
